export const ErrorCodes = {
  // auth
  AUTH_INVALID: 'AUTH_INVALID',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',

  // validation / request
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED', // ✅ NUEVO

  // users/roles (ejemplos)
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_PROTECTED: 'ROLE_PROTECTED',

  // tenancy
  TENANT_REQUIRED: 'TENANT_REQUIRED',

  // generic
  INTERNAL: 'INTERNAL',

  // sedes
  SEDE_NOT_FOUND: 'SEDE_NOT_FOUND',
  SEDE_NOMBRE_DUPLICADO: 'SEDE_NOMBRE_DUPLICADO',
  SEDE_YA_ACTIVA: 'SEDE_YA_ACTIVA',
  SEDE_YA_INACTIVA: 'SEDE_YA_INACTIVA',
  SEDE_DEBE_INACTIVARSE_ANTES_DE_ELIMINAR: 'SEDE_DEBE_INACTIVARSE_ANTES_DE_ELIMINAR',
  SEDE_INACTIVA: 'SEDE_INACTIVA',

  // puntos-retiro
  PUNTO_RETIRO_NOT_FOUND: 'PUNTO_RETIRO_NOT_FOUND',
  PUNTO_RETIRO_NOMBRE_DUPLICADO: 'PUNTO_RETIRO_NOMBRE_DUPLICADO',
  PUNTO_RETIRO_YA_ACTIVO: 'PUNTO_RETIRO_YA_ACTIVO',
  PUNTO_RETIRO_YA_INACTIVO: 'PUNTO_RETIRO_YA_INACTIVO',
  PUNTO_RETIRO_DEBE_INACTIVARSE_ANTES_DE_ELIMINAR: 'PUNTO_RETIRO_DEBE_INACTIVARSE_ANTES_DE_ELIMINAR',

  // categorias-menu
  CATEGORIA_MENU_NOT_FOUND: 'CATEGORIA_MENU_NOT_FOUND',
  CATEGORIA_MENU_NOMBRE_DUPLICADO: 'CATEGORIA_MENU_NOMBRE_DUPLICADO',
  CATEGORIA_MENU_YA_ACTIVA: 'CATEGORIA_MENU_YA_ACTIVA',
  CATEGORIA_MENU_YA_INACTIVA: 'CATEGORIA_MENU_YA_INACTIVA',
  CATEGORIA_MENU_DEBE_INACTIVARSE_ANTES_DE_ELIMINAR: 'CATEGORIA_MENU_DEBE_INACTIVARSE_ANTES_DE_ELIMINAR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
