export const ErrorCodes = {
  // auth
  AUTH_INVALID: 'AUTH_INVALID',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',

  // validation / request
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED', // ✅ NUEVO

  // users/roles (ejemplos)
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_PROTECTED: 'ROLE_PROTECTED',

  // tenancy
  TENANT_REQUIRED: 'TENANT_REQUIRED',

  // generic
  INTERNAL: 'INTERNAL',

  // sedes
  SEDE_NOT_FOUND: 'SEDE_NOT_FOUND',
  SEDE_NOMBRE_DUPLICADO: 'SEDE_NOMBRE_DUPLICADO',
  SEDE_YA_ACTIVA: 'SEDE_YA_ACTIVA',
  SEDE_YA_INACTIVA: 'SEDE_YA_INACTIVA',
  SEDE_DEBE_INACTIVARSE_ANTES_DE_ELIMINAR: 'SEDE_DEBE_INACTIVARSE_ANTES_DE_ELIMINAR',
  SEDE_INACTIVA: 'SEDE_INACTIVA',

  // puntos-retiro
  PUNTO_RETIRO_NOT_FOUND: 'PUNTO_RETIRO_NOT_FOUND',
  PUNTO_RETIRO_NOMBRE_DUPLICADO: 'PUNTO_RETIRO_NOMBRE_DUPLICADO',
  PUNTO_RETIRO_YA_ACTIVO: 'PUNTO_RETIRO_YA_ACTIVO',
  PUNTO_RETIRO_YA_INACTIVO: 'PUNTO_RETIRO_YA_INACTIVO',
  PUNTO_RETIRO_DEBE_INACTIVARSE_ANTES_DE_ELIMINAR: 'PUNTO_RETIRO_DEBE_INACTIVARSE_ANTES_DE_ELIMINAR',

  // categorias-menu
  CATEGORIA_MENU_NOT_FOUND: 'CATEGORIA_MENU_NOT_FOUND',
  CATEGORIA_MENU_NOMBRE_DUPLICADO: 'CATEGORIA_MENU_NOMBRE_DUPLICADO',
  CATEGORIA_MENU_YA_ACTIVA: 'CATEGORIA_MENU_YA_ACTIVA',
  CATEGORIA_MENU_YA_INACTIVA: 'CATEGORIA_MENU_YA_INACTIVA',
  CATEGORIA_MENU_DEBE_INACTIVARSE_ANTES_DE_ELIMINAR: 'CATEGORIA_MENU_DEBE_INACTIVARSE_ANTES_DE_ELIMINAR',

  // etiquetas-menu
  ETIQUETA_MENU_NOT_FOUND: 'ETIQUETA_MENU_NOT_FOUND',
  ETIQUETA_MENU_NOMBRE_DUPLICADO: 'ETIQUETA_MENU_NOMBRE_DUPLICADO',
  ETIQUETA_MENU_YA_ACTIVA: 'ETIQUETA_MENU_YA_ACTIVA',
  ETIQUETA_MENU_YA_INACTIVA: 'ETIQUETA_MENU_YA_INACTIVA',
  ETIQUETA_MENU_DEBE_INACTIVARSE_ANTES_DE_ELIMINAR: 'ETIQUETA_MENU_DEBE_INACTIVARSE_ANTES_DE_ELIMINAR',

  // alergenos
  ALERGENO_NOT_FOUND: 'ALERGENO_NOT_FOUND',
  ALERGENO_NOMBRE_DUPLICADO: 'ALERGENO_NOMBRE_DUPLICADO',
  ALERGENO_YA_ACTIVO: 'ALERGENO_YA_ACTIVO',
  ALERGENO_YA_INACTIVO: 'ALERGENO_YA_INACTIVO',
  ALERGENO_DEBE_INACTIVARSE_ANTES_DE_ELIMINAR: 'ALERGENO_DEBE_INACTIVARSE_ANTES_DE_ELIMINAR',

  // clientes
  CLIENTE_NOT_FOUND: 'CLIENTE_NOT_FOUND',
  CLIENTE_DNI_DUPLICADO: 'CLIENTE_DNI_DUPLICADO',
  CLIENTE_YA_BLOQUEADO: 'CLIENTE_YA_BLOQUEADO',
  CLIENTE_YA_ACTIVO: 'CLIENTE_YA_ACTIVO',

  // menus-base
  MENU_BASE_NOT_FOUND: 'MENU_BASE_NOT_FOUND',
  MENU_BASE_NOMBRE_DUPLICADO: 'MENU_BASE_NOMBRE_DUPLICADO',
  MENU_BASE_YA_ACTIVO: 'MENU_BASE_YA_ACTIVO',
  MENU_BASE_YA_INACTIVO: 'MENU_BASE_YA_INACTIVO',
  MENU_BASE_DEBE_INACTIVARSE_ANTES_DE_ELIMINAR: 'MENU_BASE_DEBE_INACTIVARSE_ANTES_DE_ELIMINAR',
  MENU_BASE_RELACION_INVALIDA: 'MENU_BASE_RELACION_INVALIDA',

  // menus-publicados
  MENU_PUBLICADO_NOT_FOUND: 'MENU_PUBLICADO_NOT_FOUND',
  MENU_PUBLICADO_TRANSICION_INVALIDA: 'MENU_PUBLICADO_TRANSICION_INVALIDA',
  MENU_PUBLICADO_PUNTOS_RETIRO_INVALIDOS: 'MENU_PUBLICADO_PUNTOS_RETIRO_INVALIDOS',
  MENU_PUBLICADO_PRECIO_INVALIDO: 'MENU_PUBLICADO_PRECIO_INVALIDO',
  MENU_PUBLICADO_FECHA_LIMITE_INVALIDA: 'MENU_PUBLICADO_FECHA_LIMITE_INVALIDA',
  MENU_PUBLICADO_SOBREPRODUCCION_INVALIDA: 'MENU_PUBLICADO_SOBREPRODUCCION_INVALIDA',
  MENU_PUBLICADO_SOLO_CANCELADO_PUEDE_ELIMINARSE: 'MENU_PUBLICADO_SOLO_CANCELADO_PUEDE_ELIMINARSE',

  // banners-promociones
  BANNER_NOT_FOUND: 'BANNER_NOT_FOUND',
  BANNER_YA_ACTIVO: 'BANNER_YA_ACTIVO',
  BANNER_YA_INACTIVO: 'BANNER_YA_INACTIVO',
  BANNER_DEBE_INACTIVARSE_ANTES_DE_ELIMINAR: 'BANNER_DEBE_INACTIVARSE_ANTES_DE_ELIMINAR',
  BANNER_FECHAS_INVALIDAS: 'BANNER_FECHAS_INVALIDAS',

  // pedidos
  PEDIDO_NOT_FOUND: 'PEDIDO_NOT_FOUND',
  PEDIDO_MENU_NO_DISPONIBLE: 'PEDIDO_MENU_NO_DISPONIBLE',
  PEDIDO_PUNTO_RETIRO_NO_HABILITADO: 'PEDIDO_PUNTO_RETIRO_NO_HABILITADO',
  PEDIDO_CAPACIDAD_AGOTADA: 'PEDIDO_CAPACIDAD_AGOTADA',
  PEDIDO_NO_CANCELABLE: 'PEDIDO_NO_CANCELABLE',
  PEDIDO_FUERA_DE_VENTANA_CANCELACION: 'PEDIDO_FUERA_DE_VENTANA_CANCELACION',
  PEDIDO_RESERVA_EXPIRADA: 'PEDIDO_RESERVA_EXPIRADA',
  PEDIDO_SOLO_PAGO_PRESENCIAL_MANUAL: 'PEDIDO_SOLO_PAGO_PRESENCIAL_MANUAL',

  // pagos
  PAGO_NOT_FOUND: 'PAGO_NOT_FOUND',
  PAGO_YA_COBRADO: 'PAGO_YA_COBRADO',
  PAGO_YA_EXISTE: 'PAGO_YA_EXISTE',

  // mercado-pago
  MERCADO_PAGO_ERROR_PREFERENCIA: 'MERCADO_PAGO_ERROR_PREFERENCIA',
  MERCADO_PAGO_FIRMA_INVALIDA: 'MERCADO_PAGO_FIRMA_INVALIDA',
  MERCADO_PAGO_WEBHOOK_LOG_NOT_FOUND: 'MERCADO_PAGO_WEBHOOK_LOG_NOT_FOUND',

  // produccion-viandas
  ORDEN_PRODUCCION_NOT_FOUND: 'ORDEN_PRODUCCION_NOT_FOUND',
  ORDEN_PRODUCCION_ESTADO_INVALIDO: 'ORDEN_PRODUCCION_ESTADO_INVALIDO',
  PRODUCCION_OBSERVACION_REQUERIDA: 'PRODUCCION_OBSERVACION_REQUERIDA',

  // stock-viandas
  STOCK_VIANDA_NOT_FOUND: 'STOCK_VIANDA_NOT_FOUND',
  STOCK_INSUFICIENTE_ENTREGAS: 'STOCK_INSUFICIENTE_ENTREGAS',
  STOCK_INSUFICIENTE_SOBRANTES: 'STOCK_INSUFICIENTE_SOBRANTES',
  STOCK_AJUSTE_INVALIDO: 'STOCK_AJUSTE_INVALIDO',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
